language: python
python:
- 3.6
addons:
  apt_packages:
  - libcups2-dev
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install flake8
- pip install coveralls
- pip install -e .
- pip install -r requirements.txt
before_script:
- flake8 ambition_reference
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=ambition_reference manage.py test
after_success:
- coveralls
notifications:
  slack:
    secure: jPgCNhj9X6B5EURTD+kB8OkfC6G8DHxGLs/IiFCgwalvN8SlGMwJ2yzopEshZpvAfJHLknjc4ByRz/5ronil+pmVgf6eLTyI8VWJeCzgK7zM5UHPeJ22Ii8CR69FpWlMunSFhJN8Y0ik4u3I8COV8rQKDnOXPvpHKtrtBWfI3rs7315qjahhhrQr8iszjPxnmexMFLxWYbUPgOksAAr/JFiB+lcSIyaCwaKLxDj6UA+5EiG25vE2khVfXd50O/xqpXSk7+5k24OhFqSuSWw/NmAcX3moLtW/l6Es35+6gZoOV5/1dFQdFfoIrsCGAv3nFn7TXLbqS+nE5jMcFm/wQYpP/bazlxQuPCwnaylH/NddODMW0/f6jTJe7Fi4wkvocl28P40k/D1LwurH5689reDQ91ZN/1lWk8V8BmtggnKiF0PFEDUE0HmenaHjQqzFp+NR3N5zZgMSvZYs/zd4ewMiaK03FrSuCfmdWc5OvMw9MNDrqGGCfEGAIE3i9UoKMCeAcT1/huLY+/znBjjHPWQZMoztCxpBwz1tZwnaSWLxCRhnOk9Q0y6Ov8P5V0IKoZj3GedJSEmElz8TkPeihwn1KnxKY706rDus1BiBh/ifVYiqQgnbs0jDjgACTEKu/Pwb6UxLwJBDiD4Q28sd3s0bYyOT71bCCrWGaftmy8g=
